### ISSUE TITLE
Container fails to build due to being unable to install torch

### ISSUE THREAD

**Issue by Renari** [kestr31/docker-stable-diffusion-webui#4]
```
#14 107.3 2023-04-05 11:00:41 (76.7 MB/s) - ‘/home/user/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors’ saved [4265146304/4265146304]
#14 107.3 
#14 107.3 Killed
#14 107.3 Traceback (most recent call last):
#14 107.3   File "/home/user/stable-diffusion-webui/launch.py", line 351, in <module>
#14 107.3     prepare_environment()
#14 107.3   File "/home/user/stable-diffusion-webui/launch.py", line 253, in prepare_environment
#14 107.3     run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
#14 107.3   File "/home/user/stable-diffusion-webui/launch.py", line 81, in run
#14 107.3     raise RuntimeError(f"""{errdesc or 'Error running command'}.
#14 107.3 RuntimeError: Couldn't install torch.
#14 107.3 Command: "/home/user/stable-diffusion-webui/venv/bin/python3" -m pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
#14 107.3 Error code: 137
```

Which seems to be failing on this line:
```
RUN \
    wget -O \
        /home/user/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors \
        https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors \
    && COMMANDLINE_ARGS="--skip-torch-cuda-test --no-download-sd-model --exit" \
        /home/user/stable-diffusion-webui/webui.sh
```
This post implies that it's because the version of python being installed by apt is to new for torch.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/4641#discussioncomment-5111667

**Comment by Renari** [comment]
It seems this is related to using github codespaces and running out of disk space.
